# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: deloy ap
        run: |
          ssh ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_DOMAIN }}
          ${{ secrets.HOST_PASSWORD }}
          cd /var/www
          pm2 stop 0
          rm -rf usthb-news
          git clone https://github.com/Nidhal-Bouzara/usthb-news.git
          cd usthb-news
          cp ../.env .
          npm install
          node ace migration:run
          node ace build
          cd build
          cp ../../.env .
          pm2 start 0
